[[constraint]]
  branch = "master"
  name = "github.com/Nomon/gonfig"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"
